# Приклад робочого процесу для створення і розгортання сайту Jekyll на GitHub Pages
name: Розгортання Jekyll з попередньо встановленими залежностями GitHub Pages

on:
  # Запускається при пушах у основну гілку
  push:
    branches: ["main"]

  # Дозволяє запускати цей робочий процес вручну з вкладки Actions
  workflow_dispatch:

# Встановлює дозволи для GITHUB_TOKEN, щоб дозволити розгортання на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Дозволяє лише одне одночасне розгортання, пропускаючи запуски, які стоять у черзі між запусками в процесі та останніми у черзі.
# Однак, НЕ скасовуйте запуски, які вже йдуть, оскільки ми хочемо дозволити цим виробничим розгортанням завершитися.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Збірка
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка
        uses: actions/checkout@v4
      - name: Налаштування Pages
        uses: actions/configure-pages@v5
      - name: Збірка з Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Завантаження артефакту
        uses: actions/upload-pages-artifact@v3

  # Розгортання
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Розгортання на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Завантажити артефакт збірки
        uses: actions/upload-artifact@v4.3.3
        with:
          # Ім'я артефакту
          name: artifact
          # Файл, директорія або шаблон зірочки, що описує, що завантажити
          path: ./_site
          # Бажана поведінка, якщо файли не знайдено за вказаним шляхом.
          if-no-files-found: warn
          # Тривалість, після якої артефакт буде видалено в днях. 0 означає використання стандартного збереження.
          retention-days: 1
          # Рівень стиснення для Zlib, який застосовується до архіву артефакту. Значення може варіюватися від 0 до 9: - 0: Без стиснення - 1: Найвища швидкість - 6: Стандартне стиснення (як у GNU Gzip) - 9: Найкраще стиснення
          compression-level: 6
          # Якщо true, артефакт з відповідним ім'ям буде видалено перед завантаженням нового. Якщо false, дія не вдасться, якщо артефакт з даним ім'ям вже існує. Не вдається, якщо артефакт не існує.
          overwrite: false

      - name: Налаштування середовища Node.js
        uses: actions/setup-node@v4.0.2
        with:
          always-auth: false
          node-version: '14.x'
          architecture: x64

      - name: Налаштування Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: 'jdk'
          check-latest: true
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}
          settings-path: ~/.m2
          overwrite-settings: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          cache: maven
          cache-dependency-path: '**/pom.xml'
          job-status: ${{ job.status }}
          token: ${{ github.token }}
          mvn-toolchain-id: my-toolchain
          mvn-toolchain-vendor: adoptopenjdk

      - name: Закриття старих питань
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: 'Це питання стало неактивним.'
          stale-pr-message: 'Цей pull request став неактивним.'
          close-issue-message: 'Це питання закрито через неактивність.'
          close-pr-message: 'Цей pull request закрито через неактивність.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'Stale'
          stale-pr-label: 'Stale'

      - name: GitHub Action для розміру JS бандлів
        uses: mikeal/bundle-size-action@1.0.0

      - name: Оновлення JSON файлу
        uses: restackio/update-json-file-action@2.1
        with:
          file: 'package.json'
          fields: '{"version": "1.0.1"}'
