# Приклад робочого процесу для створення і розгортання сайту Jekyll на GitHub Pages
name: Розгортання Jekyll з попередньо встановленими залежностями GitHub Pages

on:
  # Запускається при пушах у основну гілку
  push:
    branches: ["main"]

  # Дозволяє запускати цей робочий процес вручну з вкладки Actions
  workflow_dispatch:

# Встановлює дозволи для GITHUB_TOKEN, щоб дозволити розгортання на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Дозволяє лише одне одночасне розгортання, пропускаючи запуски, які стоять у черзі між запусками в процесі та останніми у черзі.
# Однак, НЕ скасовуйте запуски, які вже йдуть, оскільки ми хочемо дозволити цим виробничим розгортанням завершитися.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Збірка
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка
        uses: actions/checkout@v4
      - name: Налаштування Pages
        uses: actions/configure-pages@v5
      - name: Збірка з Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Завантаження артефакту
        uses: actions/upload-pages-artifact@v3

  # Розгортання
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Розгортання на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Налаштування середовища Node.js
        uses: actions/setup-node@v4.0.2
        with:
          always-auth: false
          node-version: '14.x'
          architecture: x64

      - name: Закриття старих питань
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: 'Це питання стало неактивним.'
          stale-pr-message: 'Цей pull request став неактивним.'
          close-issue-message: 'Це питання закрито через неактивність.'
          close-pr-message: 'Цей pull request закрито через неактивність.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'Stale'
          stale-pr-label: 'Stale'

      - name: GitHub Action для розміру JS бандлів
        uses: mikeal/bundle-size-action@1.0.0

      - name: Оновлення JSON файлу
        uses: restackio/update-json-file-action@2.1
        with:
          file: 'package.json'
          fields: '{"version": "1.0.1"}'

      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.3
